import { useQuery } from "@tanstack/react-query";
import { BarChart3, Download, ChevronRight } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import type { BoardReport } from "@shared/schema";

export default function BoardReport() {
  const { data: reports = [], isLoading } = useQuery<BoardReport[]>({ queryKey: ["/api/board-reports"] });

  const latest = reports[reports.length - 1];

  return (
    <div className="space-y-5 max-w-screen-xl mx-auto">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-xl font-semibold tracking-tight">Board Report</h1>
          <p className="text-sm text-muted-foreground mt-0.5 ai-pulse">AI-authored executive summary · board-ready</p>
        </div>
      </div>

      {isLoading && <Skeleton className="h-48 w-full" />}

      {latest && (
        <Card className="glow-card border-cyan-500/20">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="text-base">{latest.title}</CardTitle>
                <div className="text-xs text-muted-foreground mt-0.5">Period: {latest.period} · Generated by AI CISO</div>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-xs px-2 py-1 rounded-full bg-cyan-500/10 text-cyan-400 border border-cyan-500/20">Board-ready</span>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Risk summary */}
            <Section title="Risk Summary" color="red">
              <p className="text-sm text-muted-foreground leading-relaxed">{latest.riskSummary}</p>
            </Section>

            {/* Compliance summary */}
            <Section title="Compliance Summary" color="yellow">
              <p className="text-sm text-muted-foreground leading-relaxed">{latest.complianceSummary}</p>
            </Section>

            {/* Key actions */}
            <Section title="Key Actions for Board Approval" color="cyan">
              <ul className="space-y-2">
                {(JSON.parse(latest.keyActions) as string[]).map((action, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                    <ChevronRight size={14} className="text-cyan-400 mt-0.5 flex-shrink-0" />
                    <span>{action}</span>
                  </li>
                ))}
              </ul>
            </Section>

            {/* No SI callout */}
            <div className="rounded-md bg-secondary border border-border p-3 text-xs text-muted-foreground">
              <span className="text-cyan-400 font-semibold">This report was fully generated by the AI CISO</span> — no consultant, no systems integrator, no MSP was involved. All findings are derived directly from live platform data.
            </div>
          </CardContent>
        </Card>
      )}

      {!isLoading && reports.length === 0 && (
        <div className="text-center py-12 text-sm text-muted-foreground">
          <BarChart3 size={32} className="text-muted-foreground mx-auto mb-2" />
          No reports yet
        </div>
      )}
    </div>
  );
}

function Section({ title, color, children }: { title: string; color: "red"|"yellow"|"cyan"|"green"; children: React.ReactNode }) {
  const colors = {
    red: "text-red-400 bg-red-500/5 border-red-500/20",
    yellow: "text-yellow-400 bg-yellow-500/5 border-yellow-500/20",
    cyan: "text-cyan-400 bg-cyan-500/5 border-cyan-500/20",
    green: "text-green-400 bg-green-500/5 border-green-500/20",
  };
  return (
    <div className={`rounded-md border p-4 ${colors[color]}`}>
      <div className={`text-xs font-semibold mb-2 ${colors[color].split(" ")[0]}`}>{title}</div>
      {children}
    </div>
  );
}
